config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'} do
    get "users/login" => "users/sessions#new", :as => :users_sign_in
    get "users/logout" => "users/sessions#delete", :as => :users_sign_out
  end

  get 'home/index'

  resources :students do
    resources :scholarships, only: [:show, :index]
    resources :results
    resources :payments
  end

  root 'home#index'

end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
  has_many :results
  has_many :students, through: :results
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_scholarship, only: [:show, :edit, :update, :destroy]
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /scholarships
  # GET /scholarships.json
  def index
    @scholarships = Scholarship.all
    @student = Student.find(params[:student_id])
  end

  # GET /scholarships/1
  # GET /scholarships/1.json
  def show
    @scholarship = Scholarship.find(params[:id])
    @student = Student.find(params[:student_id])
  end

  # GET /scholarships/new
  def new
    @scholarship = Scholarship.new
  end

  # GET /scholarships/1/edit
  def edit
  end

  # POST /scholarships
  # POST /scholarships.json
  def create
    @scholarship = Scholarship.new(scholarship_params)

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully created.' }
        format.json { render :show, status: :created, location: @scholarship }
      else
        format.html { render :new }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholarships/1
  # PATCH/PUT /scholarships/1.json
  def update
    respond_to do |format|
      if @scholarship.update(scholarship_params)
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholarship }
      else
        format.html { render :edit }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.json
  def destroy
    @scholarship.destroy
    respond_to do |format|
      format.html { redirect_to scholarships_url, notice: 'Scholarship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_result
    @result = Result.find(params[:id])
  end

  def set_scholarship
    @scholarship = Scholarship.find(params[:id])
  end

  def set_student
    @student = Student.find(params[:student_id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params[:result]
    end
    def scholarship_params
      params.require(:scholarship).permit(:name, :student_staus, :string, :gender, :ethnicity, :gpa, :major, :website, :deadline, :amount, :other, :community_service)
    end

    def student_params
      params.require(:student).permit(:first_name, :last_name, :student_status, :zip_code, :gender, :ethnicity, :gpa, :major, :email, :avatar, :resume, :personal_statement, :transcript_grades, :recommendations, :other)
    end
  end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/scholarships/_form.html.erb
<%= form_for(@scholarship) do |f| %>
  <% if @scholarship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scholarship.errors.count, "error") %> prohibited this scholarship from being saved:</h2>

      <ul>
      <% @scholarship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :student_staus %><br>
    <%= f.text_field :student_staus %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :ethnicity %><br>
    <%= f.text_field :ethnicity %>
  </div>
  <div class="field">
    <%= f.label :gpa %><br>
    <%= f.text_field :gpa %>
  </div>
  <div class="field">
    <%= f.label :major %><br>
    <%= f.text_field :major %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.text_field :deadline %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_field :other %>
  </div>
  <div class="field">
    <%= f.label :community_service %><br>
    <%= f.text_field :community_service %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scholarships/edit.html.erb
<h1>Editing Scholarship</h1>

app/views/scholarships/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid bg-blue jumbotron">
  <h1>All Available Scholarships</h1>
</div>

<div class="container-fluid">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Student Status</th>
        <th>Gender</th>
        <th>Ethnicity</th>
        <th>Gpa</th>
        <th>Major</th>
        <th>Website</th>
        <th>Deadline</th>
        <th>Amount</th>
        <th>Other</th>
        <th>Community service</th>
      </tr>
    </thead>

    <tbody>
      <% @scholarships.each do |scholarship| %>
      <tr>
        <td><%= link_to "#{scholarship.name}", student_scholarship_path(id: scholarship.id) %> </td>
        <td><%= scholarship.student_status %></td>
        <td><%= scholarship.gender %></td>
        <td><%= scholarship.ethnicity %></td>
        <td><%= scholarship.gpa %></td>
        <td><%= scholarship.major %></td>
        <td id="sch_url"><%= scholarship.website %></td>
        <td><%= scholarship.deadline %></td>
        <td><%= scholarship.amount %></td>
        <td><%= scholarship.other %></td>
        <td><%= scholarship.community_service %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/scholarships/new.html.erb
<h1>New Scholarship</h1>

app/views/scholarships/show.html.erb
<div class="container-fluid jumbotron bg-blue">
  <h1>Scholarship Information</h1>
</div>


<p>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        <strong>Name:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.name %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Student staus:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.student_status %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Gender:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.gender %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Ethnicity:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.ethnicity %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Gpa:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.gpa %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Major:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.major %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Website:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.website %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Deadline:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.deadline %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Amount:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.amount %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Other:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.other %>
      </div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2">
        <strong>Community service:</strong>
      </div>
      <div class="col-sm-2">
        <%= @scholarship.community_service %>
      </div>
    </div>
  </p>

      </div>