config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'} do
    get "users/login" => "users/sessions#new", :as => :users_sign_in
    get "users/logout" => "users/sessions#delete", :as => :users_sign_out
  end

  get 'home/index'

  resources :students do
    resources :scholarships, only: [:show, :index]
    resources :results
    resources :payments
  end

  root 'home#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :results
  has_many :scholarships, through: :results
  # validates :first_name, :last_name, :email, :student_status, :zip_code, :gender, :ethnicity, :gpa, :major, presence: true

  has_attached_file :avatar, :styles => { :large => ["600x600>"], :medium => ["300x300>"], :thumb => ["100x100>"]}, default_url: "assets/avatars/:style/missing.png",                   :url  => "/assets/avatars/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/avatars/:id/:style/:basename.:extension"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_attached_file :resume, :url  => "/assets/resumes/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/resumes/:id/:style/:basename.:extension"
  # validates_attachment_content_type :resume, content_type: "resumes/pdf"

  has_attached_file :personal_statement, :url  => "/assets/personal_statement/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/personal_statement/:id/:style/:basename.:extension"
  # validates_attachment_content_type :personal_statement, content_type: "resumes/pdf"

  has_attached_file :transcript_grades, :url  => "/assets/transcript_grades/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/transcript_grades/:id/:style/:basename.:extension"
  # validates_attachment_content_type :transcript_grades, content_type: "resumes/pdf"

  has_attached_file :recommendations, :url  => "/assets/recommendations/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/recommendations/:id/:style/:basename.:extension"
  # validates_attachment_content_type :recommendations, content_type: "resumes/pdf"

  has_attached_file :other, :url  => "/assets/other/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/other/:id/:style/:basename.:extension"
  # validates_attachment_content_type :other, content_type: "resumes/pdf"

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :authenticate_user!

  load_and_authorize_resource

  # before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    # StudentMailer.welcome_email(@student).deliver_later

    # p @student.gender
  end

  # GET /students/new
  def new
    # @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    # if @student.update_attributes(student_params)
    #   redirect_to @student
    # p params
    # @current = @student
    # p @current.first_name
    @update = params[:student]
    # p @update[:first_name]
    if @update[:first_name] == @student.first_name &&
     @update[:last_name] == @student.last_name &&
     @update[:email] == @student.email &&
     @update[:student_status] == @student.student_status &&
     @update[:zip_code] == @student.zip_code &&
     @update[:gender] == @student.gender &&
     @update[:ethnicity] == @student.ethnicity &&
     @update[:gpa] == @student.gpa &&
     @update[:major] == @student.major &&
     @update[:avatar] == @student.avatar &&
     @update[:resume] == @student.resume &&
     @update[:personal_statement] == @student.personal_statement &&
     @update[:transcript_grades] == @student.transcript_grades &&
     @update[:recommendations] == @student.recommendations &&
     @update[:other] == @student.other
     redirect_to @student
   elsif @student.remove_resume == true
     @student.resume = nil
   elsif @student.remove_avatar == true
     @student.avatar = nil
   elsif @student.remove_personal_statment == true
     @student.personal_statement = nil
   elsif @student.remove_transcript_grades == true
     @student.transcript_grades = nil
   elsif @student.remove_recommendations == true
     @student.recommendations = nil
   elsif @student.remove_other == true
     @student.other = nil
   else
    @student.update(student_params)
    # p params
    # StudentMailer.welcome_email(@student).deliver_later
    render 'show'
  end
end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_result
    #   @result = Result.find(params[:id])
    # end

    # def set_scholarship
    #   @scholarship = Scholarship.find(params[:id])
    # end

    # def set_student
    #   @student = Student.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params[:result]
    end
    def scholarship_params
      params.require(:scholarship).permit(:name, :student_staus, :string, :gender, :ethnicity, :gpa, :major, :website, :deadline, :amount, :other, :community_service)
    end

    def student_params
      params.require(:student).permit(:first_name, :last_name, :student_status, :zip_code, :gender, :ethnicity, :gpa, :major, :email, :avatar, :resume, :personal_statement, :transcript_grades, :recommendations, :other, :stripe_card_token, :price)
    end
  end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_profile_form.html.erb
<%= form_for @student, :html => { :multipart => true} do |f| %>
<% if @student.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

  <ul>
    <% @student.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container-fluid text-left">
  <div class="field form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field form-group">
    <%= f.label :student_status %><br>
    <%= f.text_field :student_status %>
  </div>
  <div class="field form-group">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field form-group">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field form-group">
    <%= f.label :ethnicity %><br>
    <%= f.text_field :ethnicity %>
  </div>
  <div class="field form-group">
    <%= f.label :gpa %><br>
    <%= f.text_field :gpa %>
  </div>
  <div class="field form-group">
    <%= f.label :major %><br>
    <%= f.text_field :major %>
  </div>
  <div class="field form-group">
    <%= f.label :profile_picture %><br>
    <%= f.file_field :avatar %>
    <% if @student.avatar? %>
    <%= f.label :replace_avatar %>
    <%= f.check_box :remove_avatar, :checked => false %>
    <% end %>
  </div>
  <div class="field form-group">
    <%= f.label :resume %><br>
    <%= f.file_field :resume %>
    <% if @student.resume? %>
    <%= f.label :replace_resume %>
    <%= f.check_box :remove_resume, :checked => false %>
    <% end %>
  </div>
  <div class="field form-group">
    <%= f.label :personal_statement %><br>
    <%= f.file_field :personal_statement %>
    <% if @student.personal_statement? %>
    <%= f.label :replace_personal_statement %>
    <%= f.check_box :remove_personal_statement, :checked => false %>
    <% end %>
  </div>
  <div class="field form-group">
    <%= f.label :transcript_grades %><br>
    <%= f.file_field :transcript_grades %>
    <% if @student.transcript_grades? %>
    <%= f.label :replace_transcript_grades %>
    <%= f.check_box :remove_transcript_grades, :checked => false %>
    <% end %>
  </div>
  <div class="field form-group">
    <%= f.label :recommendations %><br>
    <%= f.file_field :recommendations %>
    <% if @student.recommendations? %>
    <%= f.label :replace_recommendations %>
    <%= f.check_box :remove_recommendations, :checked => false %>
    <% end %>
  </div>
  <div class="field form-group">
    <%= f.label :other %><br>
    <%= f.file_field :other %>
    <% if @student.other? %>
    <%= f.label :replace_other %>
    <%= f.check_box :remove_other, :checked => false %>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/students/edit.html.erb
<div class="container-fluid">
  <div class="container-fluid bg-blue">
    <h1 class="text-center">Edit Your Profile</h1>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <%= render 'profile_form' %>
    </div>

    <div class="col-sm-offset-8 ">
      <span class="glyphicon glyphicon-blackboard logo slideanim"></span>
    </div>
  </div>

</div>

app/views/students/new.html.erb
<div class="container-fluid">
  <div class="container-fluid bg-blue">
    <h1 class="text-center">Complete Your Profile</h1>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <div class="container-fluid text-left">
        <%= form_for :student, url: students_path do |f| %>
        <div class="field form-group">
          <%= f.label :first_name %><br>
          <%= f.text_field :first_name %>
        </div>
        <div class="field form-group">
          <%= f.label :last_name %><br>
          <%= f.text_field :last_name %>
        </div>
        <div class="field form-group">
          <%= f.label :email %><br>
          <%= f.text_field :email %>
        </div>
        <div class="field form-group">
          <%= f.label :student_status %><br>
          <%= f.text_field :student_status %>
        </div>
        <div class="field form-group">
          <%= f.label :zip_code %><br>
          <%= f.text_field :zip_code %>
        </div>
        <div class="field form-group">
          <%= f.label :gender %><br>
          <%= f.text_field :gender %>
        </div>
        <div class="field form-group">
          <%= f.label :ethnicity %><br>
          <%= f.text_field :ethnicity %>
        </div>
        <div class="field form-group">
          <%= f.label :gpa %><br>
          <%= f.text_field :gpa %>
        </div>
        <div class="field form-group">
          <%= f.label :major %><br>
          <%= f.text_field :major %>
        </div>
        <br>
        <div class="actions">
          <%= f.submit %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-sm-offset-8 ">
      <span class="glyphicon glyphicon-blackboard logo slideanim"></span>
    </div>
  </div>

</div>

app/views/students/show.html.erb
  <p id="notice"><%= notice %></p>

  <div class="container-fluid bg-blue jumbotron">
    <h1>MY PROFILE</h1>
  </div>

  <p>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2">
          <strong>Profile Picture:</strong>
        </div>
        <div class="col-md-2">
          <%= image_tag @student.avatar.url(:thumb) %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Subscription Plan:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.price %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>First Name:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.first_name.upcase %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Last Name:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.last_name.upcase %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Email Address:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.email %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Student Status:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.student_status.upcase %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Zip Code:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.zip_code %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Gender:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.gender.upcase %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Ethnicity:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.ethnicity.upcase %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>GPA:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.gpa %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Major:</strong>
        </div>
        <div class="col-md-2">
          <%= @student.major.upcase %>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Resume:</strong>
        </div>
        <div class="col-md-2">
          <a href="<%= @student.resume.url %>">
            <img src="/assets/Document-Icon-small_1.png" alt="Document" style="width:30px;height:30px"></img>
          </a>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Personal Statement:</strong>
        </div>
        <div class="col-md-2">
          <a href="<%= @student.personal_statement.url %>">
            <img src="/assets/Document-Icon-small_1.png" alt="Document" style="width:30px;height:30px"></img>
          </a>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Transcript/Grades:</strong>
        </div>
        <div class="col-md-2">
          <a href="<%= @student.transcript_grades.url %>">
            <img src="/assets/Document-Icon-small_1.png" alt="Document" style="width:30px;height:30px"></img>
          </a>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Recommendations:</strong>
        </div>
        <div class="col-md-2">
          <a href="<%= @student.recommendations.url %>">
            <img src="/assets/Document-Icon-small_1.png" alt="Document" style="width:30px;height:30px"></img>
          </a>
        </div>
      </div>
    </p>

    <p>
      <div class="row">
        <div class="col-md-2">
          <strong>Other:</strong>
        </div>
        <div class="col-md-2">
          <a href="<%= @student.other.url %>">
            <img src="/assets/Document-Icon-small_1.png" alt="Document" style="width:30px;height:30px"></img>
          </a>
        </div>
      </div>
    </p>

  </div>