config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'} do
    get "users/login" => "users/sessions#new", :as => :users_sign_in
    get "users/logout" => "users/sessions#delete", :as => :users_sign_out
  end

  get 'home/index'

  resources :students do
    resources :scholarships, only: [:show, :index]
    resources :results
    resources :payments
  end

  root 'home#index'

end

app/views/layouts/_user_login.html.erb
<br>
<br>
<br>
<% if user_signed_in? %>
<div class="container">
  <h4 class="text-right text-capitalize">Welcome to OneScholarship <%= current_user.email %></h4>
</div>

<br>

<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collasped_nav" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar icon_bar_color"></span>
      <span class="icon-bar icon_bar_color"></span>
      <span class="icon-bar icon_bar_color"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav navbar-right">
      <li> <button class="btn btn-default"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></button></li>
      <li>      <button class="btn btn-default">
        <%= link_to 'View My Profile', student_path(current_user) %></button></li>
        <li>        <button class="btn btn-default">
          <%= link_to 'My Results', student_results_path(current_user) %></button></li>
          <li>        <button class="btn btn-default">
            <%= link_to 'Edit My Profile', edit_student_path(current_user) %></button></li>
            <li>        <button class="btn btn-default">
              <%= link_to 'All Available Scholarships', student_scholarships_path(current_user) %></button></li>
            </ul>
          </div>

        </div>


        <% else %>
        <div class="container">
          <h4 class="text-right text-capitalize">You are not logged in.</h4>
        </div>

        <div class="container">
          <p class="text-right">
            <button class="btn btn-default"><%= link_to 'Login', new_user_session_path %></button></p>

          </div>
        </div>

        <% end %>

        <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneScholarship Rails</title>

  <meta name="viewpoint" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_tag "Stipe.publishableKey = '#{Rails.configuration.stripe[:publishable_key]}';", type: 'text/javascript' %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= render 'layouts/user_login' %>
<%= yield %>


</body>
</html>